//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BridgeStack.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BridgeStack.Resources.Error", typeof(Error).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Accessing API endpoint: {0}.
        /// </summary>
        internal static string AccessingApiEndpoint {
            get {
                return ResourceManager.GetString("AccessingApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential bad request aborted before execution..
        /// </summary>
        internal static string BadRequestParameter {
            get {
                return ResourceManager.GetString("BadRequestParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error cloning query string parameters object..
        /// </summary>
        internal static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date object value expected..
        /// </summary>
        internal static string DateExpected {
            get {
                return ResourceManager.GetString("DateExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vectorized requests require at least one element. {0}.
        /// </summary>
        internal static string EmptyVector {
            get {
                return ResourceManager.GetString("EmptyVector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception accessing API endpoint: {0}.
        /// </summary>
        internal static string ExceptionAccessingApiEndpoint {
            get {
                return ResourceManager.GetString("ExceptionAccessingApiEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer token type expected..
        /// </summary>
        internal static string IntegerTokenExpected {
            get {
                return ResourceManager.GetString("IntegerTokenExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unix epoch starts January 1st, 1970..
        /// </summary>
        internal static string InvalidUnixEpochErrorMessage {
            get {
                return ResourceManager.GetString("InvalidUnixEpochErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter requires a value. {1}.
        /// </summary>
        internal static string RequiredParameterConstraint {
            get {
                return ResourceManager.GetString("RequiredParameterConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one of the following fields needs to be set: {0}. {1}.
        /// </summary>
        internal static string RequiredParameterFieldsConstraint {
            get {
                return ResourceManager.GetString("RequiredParameterFieldsConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter value &apos;{1}&apos; does not allow Min or Max parameters in this query. {2}.
        /// </summary>
        internal static string SortMinMaxConstraint {
            get {
                return ResourceManager.GetString("SortMinMaxConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected {0} parameter Type &apos;{1}&apos;. Actual: &apos;{2}&apos;. {3}.
        /// </summary>
        internal static string SortRangeTypeConstraint {
            get {
                return ResourceManager.GetString("SortRangeTypeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} parameter does not allow &apos;{1}&apos; as a value in this query. {2}.
        /// </summary>
        internal static string SortValueConstraint {
            get {
                return ResourceManager.GetString("SortValueConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time object value expected..
        /// </summary>
        internal static string TimeExpected {
            get {
                return ResourceManager.GetString("TimeExpected", resourceCulture);
            }
        }
    }
}
